(()=>{
  const host=document.getElementById('reciclagens');
  host.innerHTML=`<div class="training-heading"><div><h1>Capacitações e reciclagens</h1><p>Turmas em grupo e histórico individual • COPPIT - ABS</p></div><button id="trainingReload" class="ghost-btn">Atualizar registros</button></div>
  <p id="trainingStatus" role="status"></p>
  <div class="training-box"><h2>Nova turma</h2><div class="training-grid">
  <label>Tema<input id="trTopic" required></label><label>Data<input id="trDate" type="date" required></label><label>Tipo<select id="trType"><option>Reciclagem</option><option>Treinamento</option><option>Orientação</option></select></label>
  <label>Instrutor<input id="trInstructor" required></label><label>Área<input id="trArea" required placeholder="Ex.: Expedição / Outbound"></label><label>Motivo<select id="trReason"><option>Preventiva / reciclagem geral</option><option>Desvio de processo</option><option>Mudança de procedimento</option><option>Tratativa de MIS SCAN</option></select></label>
  <label>Observações<input id="trNotes" maxlength="2000"></label><label>PIN de gravação<input id="trPin" type="password" autocomplete="off" placeholder="Mesmo PIN das tratativas"></label>
  </div></div>
  <div class="training-box"><h2>Participantes da COPPIT - ABS</h2><p id="trSource"></p><div class="training-grid"><label>Nome ou OPSID<input id="trSearch" type="search"></label><label>Turno<select id="trShift"><option value="">Todos</option></select></label><label>Setor<select id="trSector"><option value="">Todos</option></select></label><label>Líder<select id="trLeader"><option value="">Todos</option></select></label></div>
  <div class="training-actions"><button id="trSelect">Marcar todos do filtro</button><button id="trUnselect">Desmarcar filtro</button><button id="trClear">Limpar seleção</button><strong id="trCount" aria-live="polite"></strong></div><div id="trRoster" class="training-roster"></div><div class="training-actions"><button id="trPrev">Anterior</button><span id="trPage"></span><button id="trNext">Próxima</button></div>
  <details><summary>Inclusão em massa e atualização da lista ABS</summary><label>Cole nomes ou OPSIDs, um por linha<textarea id="trBulk" rows="4"></textarea></label><button id="trBulkAdd">Adicionar à seleção</button><p id="trBulkStatus" role="status"></p><div class="training-actions"><button id="trSync">Atualizar lista da planilha</button><label>Importar lista ABS validada (JSON)<input id="trImport" type="file" accept="application/json,.json"></label></div></details></div>
  <div class="training-box"><h2>Conferência da turma</h2><div id="trSelected" class="training-selected"></div><p>Marque somente quem participou. Esta turma não encerra automaticamente tratativas individuais de MIS SCAN.</p><label><input id="trPresence" type="checkbox"> Confirmo a presença dos participantes selecionados</label><div class="training-actions"><button id="trSave" class="primary-btn" disabled>Registrar turma</button><span id="trSaveStatus" role="status"></span></div></div>
  <div class="training-box"><h2>Turmas realizadas e histórico individual</h2><div class="training-grid"><label>Nome, OPSID ou tema<input id="trHistoryQuery" type="search"></label><label>Data inicial<input id="trHistoryFrom" type="date"></label><label>Data final<input id="trHistoryTo" type="date"></label></div><div class="training-actions"><strong id="trStats"></strong><button id="trExport">Exportar participações CSV</button></div><div id="trHistory"></div></div>`;
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
  let roster=[],events=[],selected=new Set(),page=0,loaded=false,busy=false,eventId=crypto.randomUUID();
  $('trDate').value=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  $('trPin').value=sessionStorage.getItem('misscanTreatmentWritePinV1')||'';
  function status(s){$('trainingStatus').textContent=s;}
  async function api(body){const headers={};if(body){const pin=$('trPin').value.trim();if(!pin)throw new Error('Informe o PIN de gravação.');headers['Content-Type']='application/json';headers['x-treatment-pin']=pin;}
    const response=await fetch('/api/reciclagens',{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Falha ao consultar reciclagens.');return data;}
  function filtered(){const q=norm($('trSearch').value);return roster.filter(p=>(!q||norm(p.name+' '+p.opsid).includes(q))&&(!$('trShift').value||p.shift===$('trShift').value)&&(!$('trSector').value||p.sector===$('trSector').value)&&(!$('trLeader').value||p.leader===$('trLeader').value));}
  function setRoster(data){roster=data.rows||[];const valid=new Set(roster.map(p=>p.opsid));selected=new Set([...selected].filter(id=>valid.has(id)));[['trShift','shift'],['trSector','sector'],['trLeader','leader']].forEach(([id,key])=>{const old=$(id).value;$(id).innerHTML='<option value="">Todos</option>'+[...new Set(roster.map(p=>p[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');$(id).value=old;});$('trSource').textContent=roster.length?`${roster.length} colaboradores • COPPIT - ABS • Lista sincronizada em ${new Date(data.updatedAt).toLocaleString('pt-BR')}`:'Lista ABS ainda não carregada.';render();}
  function render(){const list=filtered(),pages=Math.max(1,Math.ceil(list.length/12));page=Math.min(page,pages-1);$('trRoster').innerHTML=list.slice(page*12,page*12+12).map(p=>`<label class="training-person ${selected.has(p.opsid)?'selected':''}"><input type="checkbox" data-opsid="${esc(p.opsid)}" ${selected.has(p.opsid)?'checked':''}><span><strong>${esc(p.name)}</strong><small>${esc(p.opsid)} • ${esc(p.shift)} • ${esc(p.sector)}</small><small>Líder: ${esc(p.leader||'Não informado')}</small></span></label>`).join('')||'<p>Nenhum colaborador encontrado.</p>';$('trPage').textContent=`Página ${page+1} de ${pages} • ${list.length} nomes no filtro`;$('trPrev').disabled=page===0;$('trNext').disabled=page>=pages-1;$('trCount').textContent=`${selected.size} selecionados`;$('trSelected').innerHTML=roster.filter(p=>selected.has(p.opsid)).map(p=>`<span>${esc(p.name)} • ${esc(p.opsid)}</span>`).join('')||'Nenhum selecionado.';$('trSave').disabled=busy||!selected.size||!$('trPresence').checked;}
  function historyRows(){const q=norm($('trHistoryQuery').value);return events.filter(e=>(!$('trHistoryFrom').value||e.date>=$('trHistoryFrom').value)&&(!$('trHistoryTo').value||e.date<=$('trHistoryTo').value)).map(e=>({...e,participants:e.participants.filter(p=>!q||norm(e.topic+' '+p.name+' '+p.opsid).includes(q))})).filter(e=>e.participants.length);}
  function history(){const list=historyRows(),people=list.flatMap(e=>e.participants);$('trStats').textContent=`${list.length} turmas • ${people.length} participações • ${new Set(people.map(p=>p.opsid)).size} pessoas únicas`;$('trHistory').innerHTML=list.map(e=>`<details class="training-event"><summary><strong>${esc(e.topic)}</strong> • ${esc(e.date)} • ${e.participants.length} participantes</summary><p>${esc(e.type)} • ${esc(e.area)} • Instrutor: ${esc(e.instructor)} • ${esc(e.reason)}</p><p>${esc(e.notes)}</p><div class="training-selected">${e.participants.map(p=>`<span>${esc(p.name)} • ${esc(p.opsid)} • ${esc(p.shift)} • ${esc(p.leader)}</span>`).join('')}</div></details>`).join('')||'<p>Nenhum registro encontrado.</p>';}
  async function load(){status('Carregando lista ABS e turmas...');try{const data=await api();setRoster(data.roster);events=data.events||[];history();loaded=true;status(data.sourceError||'Registros compartilhados carregados.');}catch(e){status(e.message);}}
  document.querySelector('[data-tab="reciclagens"]').addEventListener('click',load);$('trainingReload').onclick=load;
  if(typeof setInterval==='function')setInterval(()=>{if(host.classList.contains('active')&&!busy)load();},300000);
  ['trSearch','trShift','trSector','trLeader'].forEach(id=>$(id).addEventListener(id==='trSearch'?'input':'change',()=>{page=0;render();}));
  $('trRoster').onchange=e=>{const id=e.target.dataset.opsid;if(id){e.target.checked?selected.add(id):selected.delete(id);$('trPresence').checked=false;render();}};
  $('trSelect').onclick=()=>{filtered().forEach(p=>selected.add(p.opsid));$('trPresence').checked=false;render();};$('trUnselect').onclick=()=>{filtered().forEach(p=>selected.delete(p.opsid));$('trPresence').checked=false;render();};$('trClear').onclick=()=>{selected.clear();$('trPresence').checked=false;render();};$('trPrev').onclick=()=>{page--;render();};$('trNext').onclick=()=>{page++;render();};$('trPresence').onchange=render;
  $('trBulkAdd').onclick=()=>{const unresolved=[];const ids=new Set();$('trBulk').value.split(/[\n;,]+/).map(s=>s.trim()).filter(Boolean).forEach(s=>{const matches=roster.filter(p=>norm(p.opsid)===norm(s)||norm(p.name)===norm(s));if(matches.length===1)ids.add(matches[0].opsid);else unresolved.push(s);});ids.forEach(id=>selected.add(id));$('trPresence').checked=false;$('trBulkStatus').textContent=`${ids.size} encontrados • Não encontrados ou ambíguos: ${unresolved.join(', ')||'nenhum'}`;render();};
  $('trSync').textContent='Recarregar lista sincronizada';$('trSync').onclick=load;
  $('trImport').onchange=async()=>{const file=$('trImport').files[0];if(!file)return;try{if(file.size>3000000)throw new Error('Arquivo acima de 3 MB.');const parsed=JSON.parse(await file.text());const data=await api({action:'importRoster',rows:Array.isArray(parsed)?parsed:parsed.rows});setRoster(data.roster);status('Lista ABS importada no banco compartilhado.');}catch(e){status(e.message);}finally{$('trImport').value='';}};
  $('trSave').onclick=async()=>{if(busy||!selected.size||!$('trPresence').checked)return;for(const id of ['trTopic','trDate','trInstructor','trArea'])if(!$(id).reportValidity())return;busy=true;render();$('trSaveStatus').textContent='Salvando no banco compartilhado...';try{const data=await api({action:'create',event:{id:eventId,topic:$('trTopic').value,date:$('trDate').value,type:$('trType').value,instructor:$('trInstructor').value,area:$('trArea').value,reason:$('trReason').value,notes:$('trNotes').value,participants:[...selected],presenceConfirmed:true}});events=[data.event,...events.filter(e=>e.id!==data.event.id)];history();selected.clear();$('trPresence').checked=false;eventId=crypto.randomUUID();$('trSaveStatus').textContent='Turma registrada no banco compartilhado.';}catch(e){$('trSaveStatus').textContent=e.message+' A seleção foi mantida para tentar novamente.';}finally{busy=false;render();}};
  ['trHistoryQuery','trHistoryFrom','trHistoryTo'].forEach(id=>$(id).oninput=history);
  $('trExport').onclick=()=>{const rows=historyRows().flatMap(e=>e.participants.map(p=>[e.id,e.date,e.topic,e.type,e.instructor,e.area,p.name,p.opsid,p.shift,p.sector,p.leader]));const quote=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const text=[['ID','Data','Tema','Tipo','Instrutor','Área','Colaborador','OPSID','Turno','Setor','Líder'],...rows].map(r=>r.map(quote).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='reciclagens_participantes.csv';a.click();URL.revokeObjectURL(url);};render();
})();
