(()=>{
  const host=document.getElementById('reciclagens');
  if(!host)return;
  host.innerHTML=`
  <div class="training-heading"><div><span class="training-eyebrow">COP MG4 · INSTRUTORIA DE PROCESSOS</span><h1>Capacitações e reciclagens</h1><p>Organize turmas, registre participantes e mantenha as listas de presença no mesmo lugar.</p></div><button id="trainingReload" class="ghost-btn" type="button">Atualizar registros</button></div>
  <div class="training-kpis" aria-label="Resumo das capacitações"><div><span>Turmas registradas</span><strong id="trKpiEvents">—</strong></div><div><span>Participações</span><strong id="trKpiParticipants">—</strong></div><div><span>Colaboradores capacitados</span><strong id="trKpiPeople">—</strong></div><div><span>Turmas com lista anexada</span><strong id="trKpiFiles">—</strong></div></div>
  <div class="training-navigation" role="tablist" aria-label="Capacitações"><button id="trNewTab" type="button" role="tab" aria-selected="true" aria-controls="trNewPanel">Registrar turma</button><button id="trHistoryTab" type="button" role="tab" aria-selected="false" aria-controls="trHistoryPanel">Histórico de capacitações</button></div>
  <p id="trainingStatus" class="training-status" role="status" aria-live="polite">Abra a aba para carregar os registros.</p>
  <section id="trNewPanel" role="tabpanel" aria-labelledby="trNewTab">
  <div class="training-workspace"><div class="training-main">
  <div class="training-box"><div class="training-section-heading"><span class="training-step">01</span><div><h2>Informações da turma</h2><p>Defina o tema e os dados da capacitação.</p></div></div>
  <div class="training-grid"><label class="training-wide">Tema <span class="training-required">*</span><input id="trTopic" required maxlength="2000" placeholder="Ex.: Regras de ouro — MIS SCAN na expedição"></label><label>Data <span class="training-required">*</span><input id="trDate" type="date" required></label><label>Tipo<select id="trType"><option>Reciclagem</option><option>Treinamento</option><option>Orientação</option></select></label><label>Instrutor <span class="training-required">*</span><input id="trInstructor" required maxlength="2000" placeholder="Nome do responsável"></label><label>Área <span class="training-required">*</span><input id="trArea" list="trAreas" required maxlength="2000" placeholder="Selecione ou informe a área"><datalist id="trAreas"><option value="Esteiras"><option value="Packing"><option value="Expedição / Outbound"><option value="Inbound"><option value="Goleiro / Rejeitos"><option value="Escola de Capacitação"><option value="EHA"><option value="PTS"><option value="Security"></datalist></label><label>Motivo<select id="trReason"><option>Preventiva / reciclagem geral</option><option>Desvio de processo</option><option>Mudança de procedimento</option><option>Tratativa de MIS SCAN</option></select></label><label>Duração (minutos)<input id="trDuration" type="number" min="1" max="1440" step="1" placeholder="Opcional"></label><label class="training-full">Orientações e observações<textarea id="trNotes" rows="3" maxlength="2000" placeholder="Pontos reforçados, orientações e informações relevantes"></textarea></label></div></div>
  <div class="training-box"><div class="training-section-heading"><span class="training-step">02</span><div><h2>Selecione os participantes</h2><p id="trSource">Lista de colaboradores da COPPIT - ABS.</p></div></div>
  <div class="training-grid training-filters"><label>Nome ou OPSID<input id="trSearch" type="search" placeholder="Buscar colaborador"></label><label>Turno<select id="trShift"><option value="">Todos</option></select></label><label>Setor<select id="trSector"><option value="">Todos</option></select></label><label>Líder<select id="trLeader"><option value="">Todos</option></select></label></div>
  <div class="training-actions"><button id="trSelect" type="button">Marcar todos do filtro</button><button id="trUnselect" type="button">Desmarcar filtro</button><button id="trOnlySelected" type="button" aria-pressed="false">Ver selecionados</button><button id="trClear" type="button" class="training-text-button">Limpar seleção</button><strong id="trCount" class="training-count" aria-live="polite"></strong></div>
  <div id="trRoster" class="training-roster"></div><div class="training-pagination"><button id="trPrev" type="button">Anterior</button><span id="trPage"></span><button id="trNext" type="button">Próxima</button></div>
  <details class="training-bulk"><summary>Adicionar participantes em massa</summary><p>Cole nomes completos ou OPSIDs. Nomes ambíguos precisam ser conferidos.</p><label>Um colaborador por linha<textarea id="trBulk" rows="4" placeholder="OPS123456\nNome completo"></textarea></label><button id="trBulkAdd" type="button">Adicionar à seleção</button><p id="trBulkStatus" role="status"></p></details>
  <details class="training-bulk"><summary>Fonte de colaboradores e atualização</summary><p>A lista é sincronizada automaticamente pelo ABS. A importação manual substitui o cadastro de participantes.</p><div class="training-actions"><button id="trSync" type="button">Recarregar lista sincronizada</button><label>Importar lista ABS validada (JSON)<input id="trImport" type="file" accept="application/json,.json"></label></div></details></div>
  <div class="training-box"><div class="training-section-heading"><span class="training-step">03</span><div><h2>Lista de presença</h2><p>Anexe a lista assinada ou fotos legíveis. Você também pode anexar depois, no histórico.</p></div></div><div id="trOrientationSignatures" hidden><p>Orientação: foto opcional. Assinatura obrigatória de quem orientou e de cada participante.</p><label>Assinatura de<select id="trSigner"></select></label><canvas id="trSignatureCanvas" width="900" height="260" aria-label="Campo de assinatura" style="width:100%;height:180px;background:#fff;border:1px solid #cbd5e1;touch-action:none"></canvas><div class="training-actions"><button id="trSignatureClear" type="button">Limpar campo</button><button id="trSignatureSave" type="button">Salvar assinatura</button></div><p id="trSignatureStatus" role="status"></p></div><label class="training-upload" for="trFiles"><strong>Selecionar PDF ou fotos da lista</strong><span>Até 3 arquivos · PDF, JPG ou PNG · máximo de 4 MB por arquivo</span><input id="trFiles" type="file" multiple accept="application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png"></label><div id="trFileList" class="training-files"></div><p id="trFileStatus" role="status"></p><button id="trPrint" type="button">Imprimir lista para assinatura</button></div></div>
  <aside class="training-box training-review"><div class="training-section-heading"><span class="training-step">04</span><div><h2>Conferência da turma</h2><p>Revise antes de registrar.</p></div></div><div id="trReview" class="training-review-meta"></div><div class="training-review-title"><strong>Participantes selecionados</strong><span id="trReviewCount">0</span></div><div id="trSelected" class="training-selected"></div><p class="training-help">Registre somente quem participou. A turma não encerra automaticamente tratativas individuais de MIS SCAN.</p><label class="training-confirmation"><input id="trPresence" type="checkbox"><span>Confirmo a presença dos participantes selecionados</span></label><label>PIN das tratativas<input id="trPin" type="password" autocomplete="off" placeholder="PIN de gravação e acesso aos anexos"></label><button id="trSave" type="button" class="primary-btn" disabled>Registrar turma</button><p id="trSaveStatus" role="status" aria-live="polite"></p></aside></div></section>
  <section id="trHistoryPanel" role="tabpanel" aria-labelledby="trHistoryTab" hidden><div class="training-box"><div class="training-section-heading"><div><h2>Histórico de capacitações</h2><p>Consulte as turmas, os participantes e as listas de presença.</p></div></div><div class="training-grid training-history-filters"><label class="training-wide">Nome, OPSID, tema ou instrutor<input id="trHistoryQuery" type="search" placeholder="Buscar no histórico"></label><label>Tipo<select id="trHistoryType"><option value="">Todos</option><option>Reciclagem</option><option>Treinamento</option><option>Orientação</option></select></label><label>Turno<select id="trHistoryShift"><option value="">Todos</option></select></label><label>Data inicial<input id="trHistoryFrom" type="date"></label><label>Data final<input id="trHistoryTo" type="date"></label><label>Lista de presença<select id="trHistoryEvidence"><option value="">Todas</option><option value="with">Com lista anexada</option><option value="without">Sem lista anexada</option></select></label></div><div class="training-actions"><strong id="trStats" aria-live="polite"></strong><button id="trExport" type="button">Exportar participações CSV</button><button id="trResetHistory" type="button">Limpar filtros</button></div><div id="trHistory"></div><p id="trHistoryStatus" role="status" aria-live="polite"></p><p class="training-help">Para anexar ou baixar uma lista, informe o PIN no campo abaixo.</p><label class="training-history-pin">PIN de acesso aos anexos<input id="trHistoryPin" type="password" autocomplete="off" placeholder="Mesmo PIN das tratativas"></label><input id="trHistoryFile" type="file" accept="application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png" hidden></div></section>`;
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
  const dateLabel=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('/'):s;
  const sizeLabel=n=>n<1024*1024?`${Math.ceil(n/1024)} KB`:`${(n/1024/1024).toFixed(1).replace('.',',')} MB`;
  let roster=[],events=[],selected=new Set(),page=0,busy=false,loading=false,onlySelected=false,files=[],uploadEventId='',eventId=crypto.randomUUID();
  let signatures={participants:{}},strokes=[],stroke=null;
  const canvas=$('trSignatureCanvas'),ctx=canvas.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#0b1f35';
  function clearSignature(){strokes=[];stroke=null;ctx.clearRect(0,0,canvas.width,canvas.height);}
  function signatureReady(){return !!signatures.instructor&&signatures.instructor.name===$('trInstructor').value.trim()&&[...selected].every(id=>signatures.participants[id]);}
  function signatureControls(){
    const orientation=$('trType').value==='Orientação';$('trOrientationSignatures').hidden=!orientation;
    const old=$('trSigner').value;
    $('trSigner').innerHTML='<option value="instructor">Quem orientou — '+esc($('trInstructor').value||'Instrutor')+'</option>'+roster.filter(p=>selected.has(p.opsid)).map(p=>`<option value="${esc(p.opsid)}">Quem foi orientado — ${esc(p.name)}</option>`).join('');
    if([...$('trSigner').options].some(o=>o.value===old))$('trSigner').value=old;
    $('trSignatureStatus').textContent=orientation?`Instrutor: ${signatures.instructor?.name===$('trInstructor').value.trim()?'assinado':'pendente'} · Participantes: ${[...selected].filter(id=>signatures.participants[id]).length}/${selected.size} assinados`:'';
  }
  canvas.onpointerdown=e=>{if(busy)return;canvas.setPointerCapture(e.pointerId);stroke=[];strokes.push(stroke);addPoint(e);};
  function addPoint(e){if(!stroke)return;const r=canvas.getBoundingClientRect(),point=[Math.round(Math.max(0,Math.min(900,(e.clientX-r.left)*900/r.width))),Math.round(Math.max(0,Math.min(260,(e.clientY-r.top)*260/r.height)))];const last=stroke.at(-1);stroke.push(point);if(last){ctx.beginPath();ctx.moveTo(...last);ctx.lineTo(...point);ctx.stroke();}}
  canvas.onpointermove=addPoint;canvas.onpointerup=()=>{stroke=null;};canvas.onpointercancel=()=>{stroke=null;};
  $('trSignatureClear').onclick=clearSignature;$('trSigner').onchange=clearSignature;
  $('trSignatureSave').onclick=()=>{if(busy)return;const valid=strokes.filter(s=>s.length>=2);if(!valid.length){$('trSignatureStatus').textContent='Faça a assinatura antes de salvar.';return;}
    const id=$('trSigner').value,name=id==='instructor'?$('trInstructor').value.trim():roster.find(p=>p.opsid===id)?.name;if(!name)return;
    const value={name,strokes:structuredClone(valid)};if(id==='instructor')signatures.instructor=value;else signatures.participants[id]=value;clearSignature();render();};
  $('trInstructor').oninput=()=>{delete signatures.instructor;render();};
  $('trDate').value=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  $('trPin').value=sessionStorage.getItem('misscanTreatmentWritePinV1')||'';$('trHistoryPin').value=$('trPin').value;
  function status(s,error=false){$('trainingStatus').textContent=s;$('trainingStatus').classList.toggle('training-error',error);}
  const accessPin=()=>($('trPin').value||$('trHistoryPin').value).trim();
  async function api(body){const headers={};if(body){const pin=accessPin();if(!pin)throw new Error('Informe o PIN das tratativas.');headers['x-treatment-pin']=pin;if(!(body instanceof FormData))headers['Content-Type']='application/json';}
    const response=await fetch('/api/reciclagens',{method:body?'POST':'GET',headers,body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined,cache:'no-store',signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Falha ao consultar reciclagens.');return data;}
  function filtered(){const q=norm($('trSearch').value);return roster.filter(p=>(!onlySelected||selected.has(p.opsid))&&(!q||norm(p.name+' '+p.opsid).includes(q))&&(!$('trShift').value||p.shift===$('trShift').value)&&(!$('trSector').value||p.sector===$('trSector').value)&&(!$('trLeader').value||p.leader===$('trLeader').value));}
  function setRoster(data){const previous=[...selected];roster=data.rows||[];const valid=new Set(roster.map(p=>p.opsid));selected=new Set(previous.filter(id=>valid.has(id)));if(previous.length!==selected.size){$('trPresence').checked=false;$('trSaveStatus').textContent='A lista ABS mudou. Confira os participantes antes de salvar.';}[['trShift','shift'],['trSector','sector'],['trLeader','leader']].forEach(([id,key])=>{const old=$(id).value;$(id).innerHTML='<option value="">Todos</option>'+[...new Set(roster.map(p=>p[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');$(id).value=old;});$('trSource').textContent=roster.length?`${roster.length} colaboradores · COPPIT - ABS · Atualizada em ${new Date(data.updatedAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}`:'Lista ABS ainda não carregada.';render();}
  function render(){signatureControls();const list=filtered(),pages=Math.max(1,Math.ceil(list.length/12));page=Math.max(0,Math.min(page,pages-1));$('trRoster').innerHTML=list.slice(page*12,page*12+12).map(p=>`<label class="training-person ${selected.has(p.opsid)?'selected':''}"><input type="checkbox" data-opsid="${esc(p.opsid)}" ${selected.has(p.opsid)?'checked':''} ${busy?'disabled':''}><span><strong>${esc(p.name)}</strong><small>${esc(p.opsid)} <span class="training-turn">${esc(p.shift||'Sem turno')}</span></small><small>${esc(p.sector||'Setor não informado')} · Líder: ${esc(p.leader||'Não informado')}</small></span></label>`).join('')||'<div class="training-empty"><strong>Nenhum colaborador encontrado</strong><p>Ajuste os filtros ou recarregue a lista ABS.</p></div>';$('trPage').textContent=`Página ${page+1} de ${pages} · ${list.length} no filtro`;$('trPrev').disabled=page===0;$('trNext').disabled=page>=pages-1;$('trCount').textContent=`${selected.size} selecionados`;$('trReviewCount').textContent=selected.size;$('trSelected').innerHTML=roster.filter(p=>selected.has(p.opsid)).map(p=>`<div><span><strong>${esc(p.name)}</strong><small>${esc(p.opsid)} · ${esc(p.shift)}</small></span><button type="button" data-remove-person="${esc(p.opsid)}" aria-label="Remover ${esc(p.name)}" ${busy?'disabled':''}>×</button></div>`).join('')||'<p class="training-help">Os participantes selecionados aparecerão aqui.</p>';$('trSave').disabled=busy||!selected.size||!$('trPresence').checked||($('trType').value==='Orientação'&&!signatureReady());$('trSave').textContent=busy?'Registrando turma…':'Registrar turma';$('trPrint').disabled=busy||!selected.size;$('trReview').innerHTML=`<strong>${esc($('trTopic').value||'Tema ainda não informado')}</strong><span>${esc(dateLabel($('trDate').value))} · ${esc($('trType').value)}</span><span>${esc($('trArea').value||'Área ainda não informada')}</span><span>${files.length?`${files.length} ${files.length===1?'lista/arquivo':'listas/arquivos'} para anexar`:'Sem anexo nesta etapa'}</span>`;
    ['trSelect','trUnselect','trClear','trBulkAdd','trImport','trFiles','trPresence','trPin'].forEach(id=>$(id).disabled=busy);}
  function historyRows(){const q=norm($('trHistoryQuery').value),from=$('trHistoryFrom').value,to=$('trHistoryTo').value;if(from&&to&&from>to)return[];
    return events.filter(e=>(!from||e.date>=from)&&(!to||e.date<=to)&&(!$('trHistoryType').value||e.type===$('trHistoryType').value)&&(!$('trHistoryEvidence').value||($('trHistoryEvidence').value==='with'?(e.attachments||[]).length:!(e.attachments||[]).length))).map(e=>({...e,totalParticipants:e.participants.length,participants:e.participants.filter(p=>(!$('trHistoryShift').value||p.shift===$('trHistoryShift').value)&&(!q||norm(e.topic+' '+e.instructor+' '+e.area+' '+p.name+' '+p.opsid+' '+p.leader).includes(q)))})).filter(e=>e.participants.length).sort((a,b)=>b.date.localeCompare(a.date)||String(b.createdAt).localeCompare(String(a.createdAt)));}
  function history(){if(!$('trHistoryFrom').value||!$('trHistoryTo').value||$('trHistoryFrom').value<=$('trHistoryTo').value)$('trHistoryStatus').textContent='';const list=historyRows(),people=list.flatMap(e=>e.participants);$('trKpiEvents').textContent=events.length;$('trKpiParticipants').textContent=events.reduce((n,e)=>n+e.participants.length,0);$('trKpiPeople').textContent=new Set(events.flatMap(e=>e.participants.map(p=>p.opsid))).size;$('trKpiFiles').textContent=events.filter(e=>e.attachments?.length).length;
    const oldShift=$('trHistoryShift').value;$('trHistoryShift').innerHTML='<option value="">Todos</option>'+[...new Set(events.flatMap(e=>e.participants.map(p=>p.shift)).filter(Boolean))].sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');$('trHistoryShift').value=oldShift;
    $('trStats').textContent=`${list.length} turmas · ${people.length} participações · ${new Set(people.map(p=>p.opsid)).size} pessoas únicas`;$('trExport').disabled=!list.length;
    $('trHistory').innerHTML=list.map(e=>`<details class="training-event"><summary><div><span class="training-event-type">${esc(e.type)}</span><strong>${esc(e.topic)}</strong><span class="training-event-meta">${esc(dateLabel(e.date))} · ${esc(e.area)} · ${e.participants.length===e.totalParticipants?`${e.totalParticipants} participantes`:`${e.participants.length} de ${e.totalParticipants} no filtro`}</span></div><span class="training-file-badge ${e.attachments?.length?'has-file':''}">${e.attachments?.length?'Lista anexada':'Sem lista anexada'}</span></summary><div class="training-event-content">${e.signatures?`<div class="training-event-signatures">${[e.signatures.instructor,...e.participants.map(p=>e.signatures.participants[p.opsid])].filter(Boolean).map(signature=>`<div><strong>${esc(signature.name)}</strong><svg viewBox="0 0 900 260" role="img" aria-label="Assinatura de ${esc(signature.name)}" style="width:100%;max-width:360px;background:white;border:1px solid #cbd5e1">${signature.strokes.map(stroke=>`<polyline points="${esc(stroke.map(point=>point.join(',')).join(' '))}" fill="none" stroke="#0b1f35" stroke-width="3"/>`).join('')}</svg></div>`).join('')}</div>`:''}<p><strong>Instrutor:</strong> ${esc(e.instructor)} ${e.duration?`· ${e.duration} min`:''}</p><p>${esc(e.reason)}</p><p class="training-event-notes">${esc(e.notes)}</p><div class="training-history-people">${e.participants.map(p=>`<div><strong>${esc(p.name)}</strong><small>${esc(p.opsid)} · ${esc(p.shift)} · ${esc(p.sector)} · ${esc(p.leader)}</small></div>`).join('')}</div><div class="training-event-files"><strong>Listas de presença</strong>${(e.attachments||[]).map(f=>`<button type="button" data-download="${esc(f.id)}" data-filename="${esc(f.name)}">Baixar ${esc(f.name)} <small>${sizeLabel(f.size)}</small></button>`).join('')||'<span>Nenhuma lista anexada.</span>'}<div class="training-actions"><button type="button" data-upload-event="${esc(e.id)}" ${e.attachments?.length>=3?'disabled':''}>Anexar lista de presença</button><button type="button" data-print-event="${esc(e.id)}">Imprimir lista da turma</button></div></div></div></details>`).join('')||`<div class="training-empty"><strong>${events.length?'Nenhuma turma corresponde aos filtros':'Nenhuma turma registrada ainda'}</strong><p>${events.length?'Ajuste a busca ou limpe os filtros.':'Registre uma turma para começar o histórico de capacitações.'}</p></div>`;
    if($('trHistoryFrom').value&&$('trHistoryTo').value&&$('trHistoryFrom').value>$('trHistoryTo').value)$('trHistoryStatus').textContent='A data final deve ser igual ou posterior à data inicial.';}
  async function load(){if(loading||busy)return;loading=true;$('trainingReload').disabled=true;status('Carregando participantes e turmas…');try{const data=await api();setRoster(data.roster);events=data.events||[];history();status(data.sourceError||'Registros atualizados. A lista ABS é sincronizada automaticamente.');}catch(e){status(e.name==='TimeoutError'?'A consulta demorou mais que o esperado. Tente atualizar novamente.':e.message,true);}finally{loading=false;$('trainingReload').disabled=false;}}
  document.querySelector('[data-tab="reciclagens"]').addEventListener('click',load);$('trainingReload').onclick=load;
  if(typeof setInterval==='function')setInterval(()=>{if(host.classList.contains('active')&&!busy)load();},300000);
  function panel(name){const isNew=name==='new';$('trNewPanel').hidden=!isNew;$('trHistoryPanel').hidden=isNew;$('trNewTab').setAttribute('aria-selected',String(isNew));$('trHistoryTab').setAttribute('aria-selected',String(!isNew));}
  $('trNewTab').onclick=()=>panel('new');$('trHistoryTab').onclick=()=>panel('history');
  ['trSearch','trShift','trSector','trLeader'].forEach(id=>$(id).addEventListener(id==='trSearch'?'input':'change',()=>{page=0;render();}));
  ['trTopic','trDate','trType','trArea'].forEach(id=>$(id).addEventListener('input',render));
  $('trRoster').onchange=e=>{if(busy)return;const id=e.target.dataset.opsid;if(id){e.target.checked?selected.add(id):selected.delete(id);$('trPresence').checked=false;render();}};
  $('trSelected').onclick=e=>{if(busy)return;const button=e.target.closest('[data-remove-person]');if(button){selected.delete(button.dataset.removePerson);$('trPresence').checked=false;render();}};
  $('trSelect').onclick=()=>{if(busy)return;filtered().forEach(p=>selected.add(p.opsid));$('trPresence').checked=false;render();};$('trUnselect').onclick=()=>{if(busy)return;filtered().forEach(p=>selected.delete(p.opsid));$('trPresence').checked=false;render();};$('trClear').onclick=()=>{if(busy)return;selected.clear();$('trPresence').checked=false;render();};$('trOnlySelected').onclick=()=>{onlySelected=!onlySelected;page=0;$('trOnlySelected').setAttribute('aria-pressed',String(onlySelected));render();};$('trPrev').onclick=()=>{page--;render();};$('trNext').onclick=()=>{page++;render();};$('trPresence').onchange=render;
  $('trPin').oninput=()=>{$('trHistoryPin').value=$('trPin').value;};$('trHistoryPin').oninput=()=>{$('trPin').value=$('trHistoryPin').value;};
  $('trBulkAdd').onclick=()=>{if(busy)return;const unresolved=[];const ids=new Set();$('trBulk').value.split(/[\n;,]+/).map(s=>s.trim()).filter(Boolean).forEach(s=>{const matches=roster.filter(p=>norm(p.opsid)===norm(s)||norm(p.name)===norm(s));if(matches.length===1)ids.add(matches[0].opsid);else unresolved.push(s);});ids.forEach(id=>selected.add(id));$('trPresence').checked=false;$('trBulkStatus').textContent=`${ids.size} encontrados · Não encontrados ou ambíguos: ${unresolved.join(', ')||'nenhum'}`;render();};
  $('trSync').onclick=load;
  $('trImport').onchange=async()=>{const file=$('trImport').files[0];if(!file)return;try{if(file.size>3000000)throw new Error('Arquivo acima de 3 MB.');const parsed=JSON.parse(await file.text());const data=await api({action:'importRoster',rows:Array.isArray(parsed)?parsed:parsed.rows});setRoster(data.roster);status('Lista ABS importada no banco compartilhado.');}catch(e){status(e.message,true);}finally{$('trImport').value='';}};
  function checkFiles(list,max=3){if(list.length>max)throw new Error(`Selecione até ${max} arquivos.`);for(const file of list){if(!/\.(pdf|jpe?g|png)$/i.test(file.name)||!['','application/pdf','image/jpeg','image/png'].includes(file.type))throw new Error('Use PDF, JPG ou PNG.');if(!file.size||file.size>4*1024*1024)throw new Error('Cada arquivo deve ter de 1 byte a 4 MB.');}}
  function fileList(){ $('trFileList').innerHTML=files.map((f,i)=>`<div><span><strong>${esc(f.name)}</strong><small>${sizeLabel(f.size)}</small></span><button type="button" data-remove-file="${i}" aria-label="Remover ${esc(f.name)}" ${busy?'disabled':''}>Remover</button></div>`).join('');render();}
  $('trFiles').onchange=()=>{if(busy)return;try{const combined=[...files];for(const file of $('trFiles').files||[])if(!combined.some(f=>f.name===file.name&&f.size===file.size&&f.lastModified===file.lastModified))combined.push(file);checkFiles(combined);files=combined;$('trFileStatus').textContent='Os anexos serão salvos junto com a turma.';fileList();}catch(e){$('trFileStatus').textContent=e.message;}finally{$('trFiles').value='';}};
  $('trFileList').onclick=e=>{if(busy)return;const b=e.target.closest('[data-remove-file]');if(b){files.splice(Number(b.dataset.removeFile),1);fileList();}};
  $('trSave').onclick=async()=>{if(busy||!selected.size||!$('trPresence').checked)return;if($('trType').value==='Orientação'&&!signatureReady()){$('trSaveStatus').textContent='Salve a assinatura de quem orientou e de todos os participantes.';return;}for(const id of ['trTopic','trDate','trInstructor','trArea','trDuration'])if(!$(id).reportValidity())return;
    const event={id:eventId,topic:$('trTopic').value,date:$('trDate').value,type:$('trType').value,instructor:$('trInstructor').value,area:$('trArea').value,reason:$('trReason').value,notes:$('trNotes').value,duration:$('trDuration').value,participants:[...selected],presenceConfirmed:true,...($('trType').value==='Orientação'?{signatures}:{} )};const submittedFiles=[...files];busy=true;render();$('trSaveStatus').textContent=submittedFiles.length?'Salvando turma e listas de presença…':'Salvando turma no banco compartilhado…';
    try{let body={action:'create',event};if(submittedFiles.length){body=new FormData();body.append('event',JSON.stringify(event));submittedFiles.forEach(f=>body.append('files',f));}const data=await api(body);events=[data.event,...events.filter(e=>e.id!==data.event.id)];history();selected.clear();files=[];signatures={participants:{}};clearSignature();$('trPresence').checked=false;eventId=crypto.randomUUID();fileList();$('trSaveStatus').textContent=`Turma registrada no banco compartilhado${submittedFiles.length?' com lista de presença anexada':''}. Consulte o histórico para baixar os arquivos.`;}catch(e){$('trSaveStatus').textContent=(e.name==='TimeoutError'?'O envio demorou mais que o esperado.':e.message)+' A seleção e os anexos foram mantidos para tentar novamente.';}finally{busy=false;render();}};
  ['trHistoryQuery','trHistoryFrom','trHistoryTo','trHistoryType','trHistoryShift','trHistoryEvidence'].forEach(id=>$(id).oninput=history);
  $('trResetHistory').onclick=()=>{['trHistoryQuery','trHistoryFrom','trHistoryTo','trHistoryType','trHistoryShift','trHistoryEvidence'].forEach(id=>$(id).value='');$('trHistoryStatus').textContent='';history();};
  $('trExport').onclick=()=>{const rows=historyRows().flatMap(e=>e.participants.map(p=>[e.id,e.date,e.topic,e.type,e.instructor,e.area,e.duration??'',p.name,p.opsid,p.shift,p.sector,p.leader,(e.attachments||[]).map(f=>f.name).join(' | ')]));const quote=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const text=[['ID','Data','Tema','Tipo','Instrutor','Área','Duração (min)','Colaborador','OPSID','Turno','Setor','Líder','Listas de presença'],...rows].map(r=>r.map(quote).join(';')).join('\r\n');download(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}),'reciclagens_participantes.csv');};
  function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  $('trHistory').onclick=async e=>{const button=e.target.closest('button');if(!button)return;
    if(button.dataset.uploadEvent){uploadEventId=button.dataset.uploadEvent;$('trHistoryFile').value='';$('trHistoryFile').click();return;}
    if(button.dataset.printEvent){const event=events.find(e=>e.id===button.dataset.printEvent);if(event)printList(event);return;}
    if(!button.dataset.download)return;button.disabled=true;$('trHistoryStatus').textContent='Carregando lista de presença…';
    try{const pin=accessPin();if(!pin)throw new Error('Informe o PIN de acesso aos anexos.');const response=await fetch('/api/training-files?id='+encodeURIComponent(button.dataset.download),{headers:{'x-treatment-pin':pin},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok){const result=await response.json();throw new Error(result.error||'Não foi possível baixar o anexo.');}download(await response.blob(),button.dataset.filename);$('trHistoryStatus').textContent='Lista de presença baixada.';}catch(e){$('trHistoryStatus').textContent=e.message;}finally{button.disabled=false;}};
  $('trHistoryFile').onchange=async()=>{const file=$('trHistoryFile').files[0],id=uploadEventId;if(!file||!id)return;try{checkFiles([file],1);const pin=accessPin();if(!pin)throw new Error('Informe o PIN de acesso aos anexos.');$('trHistoryStatus').textContent='Anexando lista de presença…';const body=new FormData();body.append('eventId',id);body.append('files',file);const response=await fetch('/api/training-files',{method:'POST',headers:{'x-treatment-pin':pin},body,signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Falha ao anexar lista.');events=events.map(e=>e.id===id?{...e,attachments:data.attachments}:e);history();$('trHistoryStatus').textContent='Lista de presença anexada à turma.';}catch(e){$('trHistoryStatus').textContent=e.message;}finally{$('trHistoryFile').value='';}};
  function printList(event){const participants=event.participants;if(!participants.length)return;let printArea=document.getElementById('trainingPrintArea');if(!printArea){printArea=document.createElement('div');printArea.id='trainingPrintArea';document.body.appendChild(printArea);}printArea.innerHTML=`<header><strong>COP MG4 | INSTRUTORIA DE PROCESSOS</strong><h1>LISTA DE PRESENÇA</h1></header><h2>${esc(event.topic||'Capacitação')}</h2><p>Data: ${esc(dateLabel(event.date))} | Área: ${esc(event.area)} | Tipo: ${esc(event.type)}</p><p>Instrutor: ${esc(event.instructor)} ${event.duration?`| Duração: ${esc(event.duration)} min`:''}</p><table><thead><tr><th>Nº</th><th>Colaborador</th><th>OPSID</th><th>Turno</th><th>Assinatura</th></tr></thead><tbody>${participants.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.name)}</td><td>${esc(p.opsid)}</td><td>${esc(p.shift)}</td><td class="training-print-signature"></td></tr>`).join('')}</tbody></table><p>Total de participantes: ${participants.length}</p><p>Assinatura do instrutor: __________________________________________________</p>`;window.addEventListener('afterprint',()=>printArea.remove(),{once:true});window.print();}
  $('trPrint').onclick=()=>printList({topic:$('trTopic').value,date:$('trDate').value,type:$('trType').value,instructor:$('trInstructor').value,area:$('trArea').value,duration:$('trDuration').value,participants:roster.filter(p=>selected.has(p.opsid))});render();
})();
